safe:        false
#baseurl:    /tchandra
url: http://tchandra-massage.fr

source:      .
destination: ./_site
plugins:     ./_plugins
encoding:    "utf-8"
future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   none

